# -*- coding: utf-8 -*-
"""perk_zh.py — 技能名称和描述的汉化映射."""

PERK_NAME_ZH = {
    "Adrenaline": "肾上腺素",
    "Angler (requires Throwing Net)": "渔夫（需要投网）",
    "Anticipation": "预判",
    "Axe Mastery": "斧专精",
    "Back to Basics": "返璞归真",
    "Backstabber": "背刺者",
    "Bags and Belts": "背包与腰带",
    "Battle Fervor": "战斗狂热",
    "Battle Flow": "战斗流畅",
    "Battleforged": "战铸",
    "Berserk": "狂暴",
    "Bestial Vigor": "兽性活力",
    "Between the Eyes (requires Melee Attack)": "眉心一击（需要近战攻击）",
    "Between the Ribs (Piercing Attack with Dagger)": "肋间穿刺（匕首穿刺攻击）",
    "Blade Dancer (requires Sword)": "剑舞者（需要剑）",
    "Blitzkrieg": "闪电战",
    "Bone Breaker (Blunt Attack with Mace)": "碎骨者（锤钝击）",
    "Bow Mastery": "弓专精",
    "Brawny": "健壮",
    "Bullseye (requires Ranged Weapon)": "靶心（需要远程武器）",
    "Bully (requires Melee Attack)": "欺凌（需要近战攻击）",
    "Bulwark": "壁垒",
    "Calculated Strikes": "精准打击",
    "Cheap Trick (requires Melee Attack)": "阴招（需要近战攻击）",
    "Cleaver Mastery": "砍刀专精",
    "Colossus": "巨人",
    "Combo": "连击",
    "Command": "指挥",
    "Concussive Strikes (Blunt Attack with Mace)": "震荡打击（锤钝击）",
    "Crippling Strikes": "致残打击",
    "Crossbow Mastery": "弩专精",
    "Dagger Mastery": "匕首专精",
    "Death Dealer (requires Melee AOE Attack)": "死亡使者（需要近战AOE攻击）",
    "Decisive": "果断",
    "Deep Cuts": "深度切割",
    "Deep Cuts (requires Cutting Damage)": "深度切割（需要切割伤害）",
    "Deep Impact (Blunt Attack with Hammer)": "深度冲击（锤钝击）",
    "Discovered Talent": "发现天赋",
    "Dismantle (Cutting Attack with Axe)": "拆卸（斧切割攻击）",
    "Dismemberment (Cutting Attack with Axe)": "断肢（斧切割攻击）",
    "Dodge": "闪避",
    "Double Strike (requires Melee Attack)": "双击（需要近战攻击）",
    "Duelist": "决斗者",
    "Dynamic Duo": "动态搭档",
    "En Garde (requires Sword)": "架剑（需要剑）",
    "Entrenched (requires Ranged Weapon)": "固守（需要远程武器）",
    "Executioner": "刽子手",
    "Exploit Opening": "利用空档",
    "Exude Confidence": "散发自信",
    "Family Pride": "家族荣耀",
    "Fast Adaptation": "快速适应",
    "Fearsome": "威慑",
    "Fencer (requires Fencing Sword)": "击剑手（需要击剑）",
    "Feral Rage (requires Melee Attack)": "野性狂怒（需要近战攻击）",
    "Finesse": "精巧",
    "Flail Mastery": "链枷专精",
    "Flail Spinner (requires Flail)": "链枷旋风（需要链枷）",
    "Follow Up": "追击",
    "Follow Up (requires Two-Handed Melee Weapon)": "追击（需要双手近战武器）",
    "Footwork": "步法",
    "Formidable Approach": "威猛逼近",
    "Fortified Mind": "坚定意志",
    "Fresh and Furious": "精力充沛",
    "Fruits of Labor": "劳动果实",
    "Ghostlike": "幽灵般",
    "Gifted": "天赋异禀",
    "Hammer Mastery": "锤专精",
    "Head Hunter": "猎头者",
    "Hold Steady": "稳如泰山",
    "Hybridization": "杂化",
    "Indomitable": "不屈",
    "Inspiring Presence (requires Banner)": "激励光环（需要旗帜）",
    "Iron Sights (requires Crossbow or Firearm)": "铁瞄（需要弩或火器）",
    "Juggernaut (requires Two Handed Non-Fencing Sword)": "主宰（需要双手非击剑）",
    "Kick": "踢击",
    "Killing Frenzy": "杀戮狂乱",
    "King of all Weapons (Piercing Attack with Spear)": "万兵之王（矛穿刺攻击）",
    "Kingfisher (requires Throwing Net)": "翠鸟（需要投网）",
    "Leverage (Weapon with a Max Range of 2 tiles)": "杠杆（2格射程武器）",
    "Line Breaker (Requires Shield)": "破阵者（需要盾牌）",
    "Lone Wolf": "孤狼",
    "Long Reach (requires Polearm)": "长距（需要长柄）",
    "Mace Mastery": "锤专精",
    "Man of Steel": "钢铁之躯",
    "Marksmanship (requires Ranged Weapon)": "神射手（需要远程武器）",
    "Mauler (Cutting Attack with Cleaver)": "撕裂者（砍刀切割攻击）",
    "Menacing": "威吓",
    "Mentor's Presence": "导师气场",
    "Mentor's Presence (effect)": "导师气场（效果）",
    "Mentor's Presence (skill)": "导师气场（技能）",
    "Metzger (requires Sword)": "屠夫（需要剑）",
    "Nailed It (requires Ranged Attack)": "命中要害（需要远程攻击）",
    "Nimble": "灵活",
    "Nine Lives": "九命",
    "Offhand Training": "副手训练",
    "Onslaught": "猛攻",
    "Opportunist (requires Throwing Weapon)": "机会主义者（需要投掷武器）",
    "Overwhelm": "压制",
    "Pathfinder": "探路者",
    "Pattern Recognition": "模式识别",
    "Phalanx": "方阵",
    "Phalanx (Two-Handed Weapon with Piercing Attack, or Shield)": "方阵（双手穿刺武器或盾牌）",
    "Poise": "沉着",
    "Polearm Mastery": "长柄专精",
    "Precise (requires Sword)": "精准（需要剑）",
    "Professional": "专业",
    "Promised Potential": "潜力兑现",
    "Quick Hands": "快手",
    "Rally the Troops": "集结部队",
    "Rattle (Blunt Attack with Hammer)": "震击（锤钝击）",
    "Reaper (requires Sword)": "收割者（需要剑）",
    "Rebuke": "斥责",
    "Relentless": "不懈",
    "Resilient": "韧性",
    "Return Favor (effect)": "回敬（效果）",
    "Return Favor (requires Melee Weapon or Unarmed)": "回敬（需要近战武器或徒手）",
    "Rising Star": "冉冉之星",
    "Rotation": "轮转",
    "Sanguinary (Cutting Attack with Cleaver)": "嗜血（砍刀切割攻击）",
    "Savage Strength": "蛮力",
    "Second Wind": "第二呼吸",
    "Shield Expert (Requires Shield)": "盾牌专家（需要盾牌）",
    "Shield Sergeant": "盾牌军士",
    "Skirmisher": "散兵",
    "Small Target": "小目标",
    "Soul Link": "灵魂链接",
    "Spear Mastery": "矛专精",
    "Steady Brace (requires Crossbow or Firearm)": "稳固支撑（需要弩或火器）",
    "Steel Brow": "铁额",
    "Strength In Numbers": "人多势众",
    "Student": "学生",
    "Sundering Strikes": "破甲打击",
    "Supporter": "支援者",
    "Survival Instinct": "生存本能",
    "Sweeping Strikes (requires Melee AOE Attack)": "横扫（需要近战AOE攻击）",
    "Swift Stabs (Piercing Attack with Dagger)": "疾刺（匕首穿刺攻击）",
    "Sword Mastery": "剑专精",
    "Target Practice (requires Bow)": "靶场训练（需要弓）",
    "Taunt": "嘲讽",
    "Tempo (requires Sword)": "节奏（需要剑）",
    "The Rush of Battle": "战斗冲击",
    "Through the Gaps (Piercing Attack with Spear)": "穿透缝隙（矛穿刺攻击）",
    "Through the Ranks": "穿越行列",
    "Throwing Mastery": "投掷专精",
    "Trick Shooter": "花式射击",
    "Trickster's Purses": "骗子的钱袋",
    "Underdog": "困兽犹斗",
    "Unstoppable": "势不可挡",
    "Vanquisher (requires Melee Attack)": "征服者（需要近战攻击）",
    "Vengeful Spite": "复仇怨恨",
    "Versatile Swordsman (requires Sword)": "全能剑士（需要剑）",
    "Vigilant": "警觉",
    "Vigorous Assault": "强力突击",
    "Vigorous Assault (requires Melee or Throwing Attack)": "强力突击（需要近战或投掷攻击）",
    "Weapon Master": "武器大师",
    "Wears it Well": "驾轻就熟",
    "Whirling Death (requires Flail)": "死亡旋风（需要链枷）",
}

PERK_DESC_ZH = {
    "Adrenaline": "解锁肾上腺素技能，可使角色在下一回合中先手行动。",
    "Angler (requires Throwing Net)": "投网技能不再消耗行动点，且增加命中率。",
    "Anticipation": "每场战斗前2次受到的攻击伤害大幅降低，百分比等于当前先攻值与目标先攻值的差值。",
    "Axe Mastery": "斧类武器技能提升，可触发拆卸与断肢攻击效果。",
    "Back to Basics": "基础攻击不再消耗体力。",
    "Backstabber": "从背后攻击时获得额外命中加成。",
    "Bags and Belts": "解锁两个额外背包槽位，背包中的物品不再降低最大体力（双手武器除外）。",
    "Battle Fervor": "击杀敌人后在2回合内获得伤害加成。",
    "Battle Flow": "每回合首次击杀敌人时，恢复基础最大体力的10%。",
    "Battleforged": "根据当前护甲值获得伤害减免，护甲越高减免越多。",
    "Berserk": "击杀敌人后恢复4点行动点，每回合限一次。",
    "Bestial Vigor": "每回合开始时有概率获得额外行动点。",
    "Between the Eyes (requires Melee Attack)": "近战攻击命中头部时造成额外伤害并附加晕眩。",
    "Between the Ribs (Piercing Attack with Dagger)": "匕首穿刺攻击无视目标部分护甲直接造成生命伤害。",
    "Blade Dancer (requires Sword)": "使用剑时每回合首次攻击获得额外命中与伤害。",
    "Blitzkrieg": "首回合获得额外行动点与先攻加成。",
    "Bone Breaker (Blunt Attack with Mace)": "锤钝击攻击命中时降低目标的近战防御。",
    "Bow Mastery": "弓类武器技能提升，射程与精准度增加。",
    "Brawny": "最大体力提升，体力恢复速度加快。",
    "Bullseye (requires Ranged Weapon)": "远程攻击可精准瞄准，降低目标掩护加成。",
    "Bully (requires Melee Attack)": "对状态异常的目标造成额外伤害。",
    "Bulwark": "装备盾牌时获得额外近战防御与决心加成。",
    "Calculated Strikes": "攻击命中时小幅提升下次攻击的命中率。",
    "Cheap Trick (requires Melee Attack)": "近战攻击有概率触发额外效果，如降低目标属性。",
    "Cleaver Mastery": "砍刀类武器技能提升，可触发出血与撕裂效果。",
    "Colossus": "最大生命值大幅提升。",
    "Combo": "连续命中同一目标时伤害逐步递增。",
    "Command": "提升周围友军的决心值。",
    "Concussive Strikes (Blunt Attack with Mace)": "锤钝击命中头部时造成晕眩效果。",
    "Crippling Strikes": "攻击有概率降低目标的近战或远程技能。",
    "Crossbow Mastery": "弩类武器技能提升，增加穿甲能力。",
    "Dagger Mastery": "匕首类武器技能提升，穿刺攻击效果增强。",
    "Death Dealer (requires Melee AOE Attack)": "近战AOE攻击获得命中与伤害加成。",
    "Decisive": "意志坚定时获得额外属性加成。",
    "Deep Cuts": "切割攻击造成更严重的出血效果。",
    "Deep Cuts (requires Cutting Damage)": "切割伤害造成的出血效果持续时间与伤害均提升。",
    "Deep Impact (Blunt Attack with Hammer)": "锤钝击攻击造成额外护甲伤害。",
    "Discovered Talent": "角色获得一个随机额外的天赋星。",
    "Dismantle (Cutting Attack with Axe)": "斧切割攻击可直接摧毁目标的盾牌。",
    "Dismemberment (Cutting Attack with Axe)": "斧切割攻击命中时永久降低目标的近战攻击力。",
    "Dodge": "根据先攻值获得近战与远程防御加成。",
    "Double Strike (requires Melee Attack)": "近战攻击有概率在同一回合内额外攻击一次。",
    "Duelist": "单手武器且副手无物时获得穿甲与伤害加成。",
    "Dynamic Duo": "与相邻友军协同作战时双方获得属性加成。",
    "En Garde (requires Sword)": "使用剑时格挡率提升，反击伤害增加。",
    "Entrenched (requires Ranged Weapon)": "远程武器使用者获得额外远程防御与稳定性。",
    "Executioner": "对生命值低于50%的目标造成额外伤害。",
    "Exploit Opening": "目标护甲被破坏后攻击获得额外穿甲效果。",
    "Exude Confidence": "战斗开始时提升周围友军的决心。",
    "Family Pride": "有同背景友军在场上时获得属性加成。",
    "Fast Adaptation": "每次未命中后获得命中率加成，命中后重置。",
    "Fearsome": "攻击造成士气打击的概率与效果提升。",
    "Fencer (requires Fencing Sword)": "击剑武器技能提升，灵活度与穿刺伤害增加。",
    "Feral Rage (requires Melee Attack)": "近战攻击在受伤后获得伤害加成。",
    "Finesse": "先攻值提升，暴击率增加。",
    "Flail Mastery": "链枷类武器技能提升，可无视盾牌防御。",
    "Flail Spinner (requires Flail)": "链枷可攻击周围多个目标。",
    "Follow Up": "攻击命中后下次攻击获得命中加成。",
    "Follow Up (requires Two-Handed Melee Weapon)": "双手近战武器命中后获得额外行动机会。",
    "Footwork": "解锁步法技能，可脱离控制区而不触发借机攻击。",
    "Formidable Approach": "向敌人移动时获得防御加成。",
    "Fortified Mind": "决心值大幅提升。",
    "Fresh and Furious": "战斗开始时体力全满且获得先攻加成。",
    "Fruits of Labor": "根据角色等级获得额外属性点。",
    "Ghostlike": "被击中时有一定概率完全闪避。",
    "Gifted": "立即获得额外属性点分配。",
    "Hammer Mastery": "锤类武器技能提升，护甲伤害大幅增加。",
    "Head Hunter": "命中头部后确保下一次攻击也命中头部。",
    "Hold Steady": "受到伤害后获得临时决心与防御加成。",
    "Hybridization": "近战与远程技能的属性加成可相互部分共享。",
    "Indomitable": "解锁不屈技能，大幅降低受到的伤害。",
    "Inspiring Presence (requires Banner)": "装备旗帜时大幅提升周围友军决心。",
    "Iron Sights (requires Crossbow or Firearm)": "弩或火器的精准度与有效射程提升。",
    "Juggernaut (requires Two Handed Non-Fencing Sword)": "双手非击剑武器获得额外伤害与穿甲。",
    "Kick": "解锁踢击技能，可将敌人推开。",
    "Killing Frenzy": "击杀敌人后在2回合内获得大幅伤害加成。",
    "King of all Weapons (Piercing Attack with Spear)": "矛穿刺攻击获得额外命中与穿甲。",
    "Kingfisher (requires Throwing Net)": "投网命中后下次攻击必中且有额外伤害。",
    "Leverage (Weapon with a Max Range of 2 tiles)": "2格射程武器攻击获得额外伤害。",
    "Line Breaker (Requires Shield)": "装备盾牌时可突破敌人阵线，推开目标。",
    "Lone Wolf": "周围无友军时获得大幅属性加成。",
    "Long Reach (requires Polearm)": "长柄武器攻击范围与命中率提升。",
    "Mace Mastery": "锤类武器技能提升，钝击效果增强。",
    "Man of Steel": "最大护甲值提升，护甲恢复速度加快。",
    "Marksmanship (requires Ranged Weapon)": "远程攻击精准度大幅提升。",
    "Mauler (Cutting Attack with Cleaver)": "砍刀切割攻击造成严重的持续出血。",
    "Menacing": "近战攻击有概率造成恐惧效果。",
    "Mentor's Presence": "周围的低级友军获得经验加成。",
    "Mentor's Presence (effect)": "导师气场效果：经验加成。",
    "Mentor's Presence (skill)": "导师气场技能：主动施放经验加成。",
    "Metzger (requires Sword)": "剑攻击对低护甲目标造成额外伤害。",
    "Nailed It (requires Ranged Attack)": "远程攻击暴击率与暴击伤害提升。",
    "Nimble": "护甲越低获得的伤害减免越高。",
    "Nine Lives": "受到致命伤害时有一次免死机会并恢复部分生命。",
    "Offhand Training": "副手武器或盾牌的使用效率提升。",
    "Onslaught": "连续攻击同一目标时获得递增的伤害加成。",
    "Opportunist (requires Throwing Weapon)": "投掷武器对移动中的目标造成额外伤害。",
    "Overwhelm": "攻击命中后降低目标的全属性，可叠加。",
    "Pathfinder": "所有地形的移动行动点消耗减少1点，最低为每格2点。",
    "Pattern Recognition": "观察敌人后可预判其攻击模式，获得防御加成。",
    "Phalanx": "与相邻持盾友军形成方阵，互相获得防御加成。",
    "Phalanx (Two-Handed Weapon with Piercing Attack, or Shield)": "双手穿刺武器或持盾时与友军协同获得防御加成。",
    "Poise": "先攻与决心值同时提升。",
    "Polearm Mastery": "长柄武器技能提升，攻击范围与伤害增加。",
    "Precise (requires Sword)": "剑攻击获得额外命中与暴击率。",
    "Professional": "所有技能获得小幅加成。",
    "Promised Potential": "升级时获得的属性成长提升。",
    "Quick Hands": "可在不消耗行动点的情况下切换武器。",
    "Rally the Troops": "解锁集结技能，可稳定动摇的友军。",
    "Rattle (Blunt Attack with Hammer)": "锤钝击攻击造成额外决心伤害。",
    "Reaper (requires Sword)": "剑攻击击杀后可立即再行动。",
    "Rebuke": "受到攻击时有概率使攻击者动摇。",
    "Relentless": "体力越低先攻值越高。",
    "Resilient": "受到的负面状态效果持续时间缩短。",
    "Return Favor (effect)": "回敬效果：被攻击后自动反击。",
    "Return Favor (requires Melee Weapon or Unarmed)": "被近战攻击后自动进行反击。",
    "Rising Star": "作为新人，战后的经验获得加成。",
    "Rotation": "解锁轮转技能，可与友军交换位置。",
    "Sanguinary (Cutting Attack with Cleaver)": "砍刀切割攻击造成大面积出血。",
    "Savage Strength": "近战伤害获得力量属性加成。",
    "Second Wind": "体力低于一半时自动恢复部分体力。",
    "Shield Expert (Requires Shield)": "盾牌防御效果大幅提升。",
    "Shield Sergeant": "装备盾牌时周围友军获得额外防御加成。",
    "Skirmisher": "轻型护甲使用者获得额外移动范围。",
    "Small Target": "体型较小的目标更难被远程攻击命中。",
    "Soul Link": "与指定友军建立灵魂链接，分担伤害。",
    "Spear Mastery": "矛类武器技能提升，穿刺与墙矛效果增强。",
    "Steady Brace (requires Crossbow or Firearm)": "弩或火器架起后精准度与伤害大幅提升。",
    "Steel Brow": "免疫暴击的额外伤害。",
    "Strength In Numbers": "周围友军越多，决心值越高。",
    "Student": "经验获得速度提升，升级更快。",
    "Sundering Strikes": "攻击额外破坏目标的护甲。",
    "Supporter": "站在友军身后时可提供属性加成。",
    "Survival Instinct": "生命值极低时获得大幅防御与决心加成。",
    "Sweeping Strikes (requires Melee AOE Attack)": "近战AOE攻击的范围与伤害提升。",
    "Swift Stabs (Piercing Attack with Dagger)": "匕首穿刺攻击速度与穿甲效果提升。",
    "Sword Mastery": "剑类武器技能提升，命中与格挡增加。",
    "Target Practice (requires Bow)": "弓类武器的精度与有效射程提升。",
    "Taunt": "解锁嘲讽技能，迫使目标攻击自己。",
    "Tempo (requires Sword)": "剑攻击命中后获得先攻加成。",
    "The Rush of Battle": "战斗中战斗节奏加快，行动点恢复加速。",
    "Through the Gaps (Piercing Attack with Spear)": "矛穿刺攻击可穿透护甲的缝隙。",
    "Through the Ranks": "可从友军后方攻击，不受阻挡。",
    "Throwing Mastery": "投掷武器技能提升，伤害与精准度增加。",
    "Trick Shooter": "远程攻击可使用特殊技巧，如跳弹射击。",
    "Trickster's Purses": "战斗开始时获得额外弹药或特殊道具。",
    "Underdog": "被包围时获得大幅近战防御加成。",
    "Unstoppable": "不受击退与控制效果影响。",
    "Vanquisher (requires Melee Attack)": "近战攻击对已受伤目标造成额外伤害。",
    "Vengeful Spite": "友军被击杀后获得大幅伤害与决心加成。",
    "Versatile Swordsman (requires Sword)": "剑类武器可根据战斗需要切换攻防模式。",
    "Vigilant": "先攻值大幅提升，不易被偷袭。",
    "Vigorous Assault": "全力攻击造成额外伤害但消耗额外体力。",
    "Vigorous Assault (requires Melee or Throwing Attack)": "近战或投掷的全力攻击造成额外伤害。",
    "Weapon Master": "所有武器技能获得小幅加成。",
    "Wears it Well": "护甲与头盔的重量惩罚降低。",
    "Whirling Death (requires Flail)": "链枷可攻击周围所有目标。",
}

def get_perk_name_zh(en_name):
    """获取技能的中文名，无翻译时返回原名。"""
    return PERK_NAME_ZH.get(en_name, en_name)

def get_perk_desc_zh(en_name):
    """获取技能的中文描述，无翻译时返回空字符串。"""
    return PERK_DESC_ZH.get(en_name, "")
